---
apiVersion: config.openshift.io/v1
kind: Build
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  buildDefaults:
    imageLabels:
    - name: prodbuild
      value: "true"
